# Site
repository: minseokLim/minseokLim.github.io
# favicon: images/favicon.ico

# Personal info
name: 임민석
title: Java 개발자 
email: mslim8803@naver.com
website: mslim8803.tistory.com

# Social links
# twitter_username: facespics
github_username: minseokLim
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 오랜 방황 끝에 <mark>천직</mark>을 찾은 늦깎이 개발자입니다. 3년차 Java 개발자이며 <mark>Spring Framework, MariaDB, Oracle, Tomcat, CentOS, Javascript</mark> 등을 활용한 풀스택 개발을 주로 해왔습니다. 코드 품질에 관심이 많고, 보다 효율적이면서 유지보수가 용이한 프로그래밍을 하기 위해 끊임없이 노력하고 공부하고 있습니다. 현재 <mark>Spring Boot, Spring Cloud, JPA, Travis CI, Nginx, AWS ECS</mark> 등을 활용한 <mark>마이크로서비스 아키텍처 개인 프로젝트</mark>를 진행하고 있습니다.

  개인프로젝트 관련 URI:
    - REST API 문서 : <a href="https://api.mslim8803.shop/api-docs.html" target="_blank">https://api.mslim8803.shop/api-docs.html</a>
    - 클라이언트 서버 : <a href="https://mslim8803.shop" target="_blank">https://mslim8803.shop</a>
    - Git 저장소 : <a href="https://github.com/minseokLim/ws-project" target="_blank">https://github.com/minseokLim/ws-project</a>&nbsp;&nbsp;&nbsp;<a href="https://github.com/minseokLim/ws-project-client" target="_blank">https://github.com/minseokLim/ws-project-client</a> 

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education 

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
